version: '3.4'
services:
  queue:
    image: nats:1.4.1-linux
    hostname: paperboy_queue
  push-service:
    build:
      context: paperboy-push-service
      target: development
    ports:
      - "8081:8080"
    environment: 
      CONFIG: nats
    depends_on:
      - queue
    volumes:
      - ./paperboy-push-service/src:/home/node/app/src:ro,consistent
      - ./paperboy-push-service/config:/home/node/app/config:ro,consistent