version: '3.4'
services:
  queue:
    image: rabbitmq:3.8.2-management
    hostname: paperboy_queue
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
    - "15672:15672"
    - "5672:5672"
  frontend:
    build: paperboy-core
    environment:
      QUEUE_URI: amqp://admin:admin@queue:5672
  push-service:
    build:
      context: paperboy-push-service
      target: development
    ports:
    - "8080:8080"
    environment:
      CONFIG: rabbitmq
    depends_on:
    - queue
    volumes:
    - ./paperboy-push-service/src:/home/node/app/src:ro,consistent
    - ./paperboy-push-service/config:/home/node/app/config:ro,consistent
