version: "3.4"
services:
  queue:
    image: nats:2.1.7-scratch
    hostname: paperboy_queue
  frontend:
    build: paperboy-core
    environment:
      QUEUE_URI: nats://queue:4222
    ports:
      - "4222:4222"
  push-service:
    build:
      context: paperboy-push-service
      target: development
    ports:
      - "8080:8080"
    environment:
      CONFIG: nats
    depends_on:
      - queue
    volumes:
      - ./paperboy-push-service/src:/home/node/app/src:ro,consistent
      - ./paperboy-push-service/config:/home/node/app/config:ro,consistent
