{{- if .Values.nats.createCluster -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "paperboy.fullname" . }}-nats
  labels:
{{ include "paperboy.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 4222
      targetPort: 4222
      protocol: TCP
  selector:
    app: nats
    nats_cluster: {{ include "paperboy.fullname" . }}-nats
{{- end }}