{{- if .Values.previewPushService.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "paperboy.previewPushService.name" . }}-config
  labels:
{{ include "paperboy.labels" . | indent 4 }}
data:
  kubernetes.env: {{ tpl (.Files.Get "preview-push-service.env") . | b64enc }}
{{- end -}}