apiVersion: v1
kind: Secret
metadata:
  name: {{ include "paperboy.pushService.name" . }}-config
  labels:
{{ include "paperboy.labels" . | indent 4 }}
data:
  kubernetes.env: {{ tpl (.Files.Get "push-service.env") . | b64enc }}
