{{- if .Values.previewPushService.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "paperboy.previewPushService.name" . }}
  labels:
{{ include "paperboy.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app.kubernetes.io/name: {{ include "paperboy.previewPushService.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end -}}