{{- if .Values.imagePullSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "paperboy.pull-secret-name" . }}
  labels:
{{ include "paperboy.labels" . | indent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
