image:
  repository: neoskop/paperboy-push-service
  tag: 2.9.1
  pullPolicy: IfNotPresent
resources:
  requests:
    memory: 50Mi
    cpu: 100m
  limits:
    memory: 100Mi
replicaCount: 2
pushService:
  token: ""
  ingress:
    enabled: false
    annotations: {}
    labels: {}
    hosts: []
previewPushService:
  enabled: true
  token: ""
  ingress:
    enabled: false
    annotations: {}
    labels: {}
    hosts: []
nats:
  createCluster: true
  url: null
  size: 3
  version: 2.9.22
nameOverride: ""
fullnameOverride: ""
imagePullSecret: {}
nodeSelector: {}
tolerations: []
affinity: {}
