image:
  repository: neoskop/paperboy-push-service
  tag: 2.6.0
  pullPolicy: IfNotPresent
resources:
  requests:
    memory: 50Mi
    cpu: 100m
  limits:
    memory: 100Mi
replicaCount: 2
pushService:
  token: ""
previewPushService:
  enabled: true
  token: ""
nats:
  createCluster: true
  url: null
  size: 3
  version: 2.1.7
nameOverride: ""
fullnameOverride: ""
nodeSelector: {}
tolerations: []
affinity: {}
